### ISSUE TITLE
Please pester valve to hire people who actually play TF2 to maintain it. They make billions, they can afford to hire more and stop contracting out their crunches.

### ISSUE THREAD

**Issue by Codefreak64** [PazerOP/tf2_bot_detector#180] opened 2020-08-08 02:01 UTC
Since other threads regarding this issue have now piled up with comments, and were originally never about the true issue, I thought I'd make a new, clean thread.

Most of you have by now heard of PazerOP's Bot Detector.

It is strongly recommended that you do not use this script.

This script can and will be abused.

The TF2 community is in grave danger, and we must all spread this information.

If this script gains too much attention and users, the owner of the script will have FULL POWER over the players.

This sounds crazy, but it is true. Not even Valve will be able to save us!
If everyone were to use this script, the owner could add whoever he wants to the blacklist.

If we let this happen, the owner will have the power of Valve in his hands. He will be able to ban ANYONE he wants to!

Please advocate against this dangerous script whenever and wherever you see it mentioned.

For further information, please read through these threads if you haven't yet.

https://steamcommunity.com/app/440/discussions/0/2798377186389969969/?ctp=7

https://steamcommunity.com/app/440/discussions/0/2798376797410238545/?ctp=6

**Comment by PazerOP** [comment] 2020-08-08 02:02
Duplicate of #179.

Do not make identical duplicates of issues.

**Closed by PazerOP** 2020-08-08 02:02 UTC
