### ISSUE TITLE
[BUG] "Unable to find +hostport"

### ISSUE THREAD

**Issue by souljaboycrankdat** [PazerOP/tf2_bot_detector#334] opened 2021-06-25 01:57 UTC
I was trying to do the current work around to get the bot detector to work after the update, but no matter what number I use of hostports it doesn't work. I've tried over 20 different types of number combinations at this point and I'm still shit out of luck, any help is deeply appreciated.

**Comment by UAVXP** [comment] 2021-06-25 02:05
Related to #331

**Comment by PazerOP** [comment] 2021-06-25 03:12
Duplicate of #331

**Closed by PazerOP** 2021-06-25 03:12 UTC
Labels: Priority: Medium, Type: Bug

**Comment by souljaboycrankdat** [comment] 2021-06-25 05:28
How is this a duplicate lmfao, you guys clearly didn't read what I had to say. Every launch option worked except for the +hostport command.

**Comment by UAVXP** [comment] 2021-06-25 08:05
Watch the mentioned issue's screenshot.

**Comment by souljaboycrankdat** [comment] 2021-06-25 10:00
> 
> 
> Watch the mentioned issue's screenshot.

I know lol, I'll send a screenshot of mine so you understand what I'm saying. I should've done this in the beginning and I apologize for it.
[https://i.imgur.com/PhaQqor.png](url)

**Comment by PazerOP** [comment] 2021-06-25 14:35
What numbers were you using for hostport? Were they less than 65535?

**Comment by PazerOP** [comment] 2021-06-26 02:45
> 
> 
> How is this a duplicate lmfao, you guys clearly didn't read what I had to say. Every launch option worked except for the +hostport command.

Also, this was marked as a duplicate because it is ultimately caused by the user trying to do a workaround for a bug that has since been fixed. The user shouldn't have to do tedious/error prone stuff like this in the first place, the program should just work.
