### ISSUE TITLE
Auto-report accounts of bots to Valve upon discovery in-game

### ISSUE THREAD

**Issue by elv3e** [PazerOP/tf2_bot_detector#228] opened 2020-11-11 19:20 UTC
I know that according to Valve's own site, they don't issue VAC bans based on reports alone; just for "tracking and statistics purposes". However, that might be precisely the problem, since not enough people bother to report hacker accounts to Valve in the wake of a kick vote (even if data was gathered via successful kick votes, the bots leave right before the vote actually goes through, rendering the vote unsuccessful), so Valve might not be aware of how widespread the problem is. If their reporting system regarding TF2 was flooded with credible complaints of the thousands of bots, however, it might force their hand in a way that actually fixes the problem.

**Comment by Barmem** [comment] 2020-11-12 00:14
Automatic reporting is against steam TOS

**Comment by Czechball** [comment] 2020-11-12 01:10
SteamIDs are already recorded in JSON playerlists in the cfg folder.

**Comment by Kenajcrap** [comment] 2020-11-12 01:13
its time consuming and unintuitive to use the personal player list to see recent flags. And its much more time consuming if that is a hacker you already had flagged some time ago. I can see how a simple player history of the last TF2 launch or last day could be useful

**Comment by ClusterConsultant** [comment] 2020-11-12 02:30
Dupe of #140 and #111

**Closed by ClusterConsultant** 2020-11-12 02:30 UTC
