### ISSUE TITLE
Allow users to modify "Warn Other Team" in settings.json

### ISSUE THREAD

**Issue by jazrak** [PazerOP/tf2_bot_detector#123] opened 2020-07-04 06:49 UTC
It would be nice if users were allowed to modify the "Warn Other Team" string (begins with "Heads up! A known hacker is joining...") in the settings.json file or otherwise. Perhaps provide a simple template the user can follow ("A hacker named %s is joining your team!").

**Comment by ClusterConsultant** [comment] 2020-07-04 07:11
Duplicate of #70

**Closed by ClusterConsultant** 2020-07-04 07:12 UTC
