### ISSUE TITLE
Fake In-Game Name Detection

### ISSUE THREAD

**Issue by MiahStone3** [PazerOP/tf2_bot_detector#356] opened 2021-08-02 07:22 UTC
**A clear and concise description of what the problem is.**
What I mean by "fake name" is when their in-game name while on the server does not match their actual Steam profile name. Most of the bots we've been seeing throughout many months use this type of cheat, most notably the "name stealing" bots. Player cheaters are also using this just as often as well.

**Describe the solution you'd like**
Detection of the player name discrepancy by comparing the in-game name to the Steam profile name and marking them as a "cheater", or at least "suspicious". 
Maybe also an alert option to tell others of the discrepancy?

**Comment by ClusterConsultant** [comment] 2021-08-02 07:35
I'm not sure if this is a straight dupe of #218 but it is certainly tightly coupled given comparing in game to steam name seems to be the core of that issue. If you want to leave this open I'll respect that, but I have a feeling these would get closed by the same future commit.

**Comment by meep2k** [comment] 2021-08-02 07:58
i think this is just asking for accounts with a naming discrepancy to be auto-marked as suspicious

**Comment by MiahStone3** [comment] 2021-08-02 08:14
#218 mainly talks about copied names with added characters, but I meant more about how the in-game names of many bots and player cheaters themselves doesn't even match with the Steam profile name (ex. [Scoreboard of name stealing bot and victim](https://i.imgur.com/IzLFM36.jpg), [bot profile](https://i.imgur.com/bHTi55c.png)) I'm not entirely sure how it is done, if the name changing is done very quickly along with clearing name history or not.

Although one issue I realize right now with the idea is that an innocent player may decide to change their Steam profile name while on a server and cause an unintentional discrepancy.

**Comment by MiahStone3** [comment] 2021-08-02 08:20
Ah wait, #218 did pretty much go over this

**Comment by ClusterConsultant** [comment] 2021-08-02 08:21
The current understanding of how #218 would be accomplished is via comparing in game name to in game name and other in game names. That first step of comparing in game to steam is what I'm getting at here. It's effectively what you are describing here. 

If you want to learn the specifics of how cheats accomplish this you can ask in the discord, it's not particularly relevant here

**Closed** 2021-08-02 20:04 UTC
Labels: Priority: Low, Type: Enhancement
