### ISSUE TITLE
Spamming Votekick when timelimit has not ran out

### ISSUE THREAD

**Issue by Ignited550** [PazerOP/tf2_bot_detector#168] opened 2020-07-29 02:48 UTC
Sometimes when 2 cheaters are on your team, the side of your screen will get spammed with "you cant votekick yet" I once even got kicked for issuing too many commands

**Comment by empirebuilder1** [comment] 2020-07-30 21:00
Official Casual servers have a votekick timeout of 2 minutes, if a kick is successfully called the tool needs to pause the votekick commands at least that long. Is there a way for the tool to determine when it has successfully called a votekick vs when the command was sent but denied by the server?

**Comment by Ignited550** [comment] 2020-07-30 21:05
> Official Casual servers have a votekick timeout of 2 minutes, if a kick is successfully called the tool needs to pause the votekick commands at least that long. Is there a way for the tool to determine when it has successfully called a votekick vs when the command was sent but denied by the server?

If the votekick is not successful, it still requires a timeout

**Comment by PazerOP** [comment] 2020-07-30 21:14
The main reason this hasn't been implemented yet is because I didn't get to it before feature freeze for v1.1. I'll prioritize it for the next version though.

**Comment by PazerOP** [comment] 2020-07-30 21:17
This is still an important issue, I think. Issues should only be closed if the tasks associated with them are completed, or the issue is invalid somehow.

**Comment by Ignited550** [comment] 2020-08-10 18:48
Can I safely close this now?

**Comment by PazerOP** [comment] 2020-08-10 20:29
No, this is not implemented yet. I will close this when it is fixed.

**Comment by kotx** [comment] 2020-08-24 18:23
A setting for "votekick call cooldown" could be added.

**Comment by 107zxz** [comment] 2020-09-09 03:52
If its a constant 2 minutes, some manual delay could be implemented, being the 2 minutes plus the time for a votekick to time out.

**Comment by Kenajcrap** [comment] 2020-09-09 19:04
> If its a constant 2 minutes, some manual delay could be implemented, being the 2 minutes plus the time for a votekick to time out.
I can see this being implemented as a "sleep" command, when you see that your votekick didn't succeed you could press a bind that would time 2 minutes before attempting a new votekick. Pressing the bind again while the timer is still counting would "wake" BD prematurely, which I can see being used in the event you switch sessions early or accidentally press the bind.

**Comment by kotx** [comment] 2020-09-10 00:09
> > If its a constant 2 minutes, some manual delay could be implemented, being the 2 minutes plus the time for a votekick to time out.
> 
> I can see this being implemented as a "sleep" command, when you see that your votekick didn't succeed you could press a bind that would time 2 minutes before attempting a new votekick. Pressing the bind again while the timer is still counting would "wake" BD prematurely, which I can see being used in the event you switch sessions early or accidentally press the bind.

This doesn't seem like something that should be done manually. I think the timer should be customizable via a setting. A tool like this should require minimal user interaction IMHO. I usually just leave this running in the background when I play the game.

**Comment by Kenajcrap** [comment] 2020-09-10 01:01
> > I can see this being implemented as a "sleep" command, when you see that your votekick didn't succeed you could press a bind that would time 2 minutes before attempting a new votekick. Pressing the bind again while the timer is still counting would "wake" BD prematurely, which I can see being used in the event you switch sessions early or accidentally press the bind.
> 
> This doesn't seem like something that should be done manually. I think the delay should be customizable via a setting. A tool like this should require minimal user interaction IMHO. I usually just leave this running in the background when I play the game.

I agree with the minimal user interaction thing, I was thinking about it while typing my comment, however then we come back to the same problem, there is no known way to detect the current status of a votekick (if yours went through, if you are on cooldown, if there is another one going on at the same time so yours errors out) with the log files. And on my mind any delay that doesn't feel "spammy" when i'm on cooldown will be too slow if that isn't the case. The only ways I can see this being solved is a manual action by the player or someone figuring out a non-intrusive way to detect the status of votekicks. In the future, if we can interact with the program by binds like is being suggested on #205, this interaction would be less cumbersome, but of couse, an automatic solution would be much better.

**Comment by 107zxz** [comment] 2020-09-10 01:07
As I said in my original suggestion, just make it the cooldown time + the time for a vote to time out. That means even if the vote passes super quickly you'll only be losing ~15 seconds

**Comment by Kenajcrap** [comment] 2020-09-10 01:09
> 
> 
> As I said in my original suggestion, just make it the cooldown time + the time for a vote to time out. That means even if the vote passes super quickly you'll only be losing ~15 seconds

that doesn't account for the times when another vote is already in progress when yours is called, which is likely considering many bots call a vote right after joining. So in that case the BD would wait more than 2 minutes before calling a vote without a reason

**Comment by ClusterConsultant** [comment] 2020-09-13 08:23
Without some kind of wild and fragile logic I don't see how this would be possible without demo parsing. I'm going to remove this from the 1.2 milestone since demo parsing is out of scope for this dev cycle.

**Comment by RedxYeti** [comment] 2021-01-02 20:26
Pazer stated in my duplicate of this issue that there's some technical issues with this bug because you cant tell in console who started the vote/who its against. I have a slightly crude idea that may work for a fix.

When the bot sends out the command to attempt the vote kick, you could have a generic command go with it, like a help command, sort of like a ping. (or maybe even just the auto generated password, which would return as unknown command) Then if the bot sees the pong of that generic command and vote kick started, it can start a 2 minute cooldown and you can attach anything else to that such as chat messages warning there's still a cheater.

It wouldn't be perfect but it could be a temporary band aid.

**Comment by ClusterConsultant** [comment] 2021-01-02 20:34
Whether or not the attempt to start a votekick is successful the companion command would be passed to console.

**Comment by RedxYeti** [comment] 2021-01-02 20:49
> Whether or not the attempt to start a votekick is successful the companion command would be passed to console.

But if the bot detector could see a vote started and the companion command at the same time, then it would start the cooldown. if it didn't see both at the same time it would just start sending attempts to vote again.

I feel like the chances are pretty low that someone else starts a vote at the same time as the detector, before the detector can verify it started the vote with the companion command. So I guess I'm saying: any vote started + companion>start cooldown

(I'm obviously no expert on how this works and I'm not trying to argue, just trying to help.)

**Comment by kotx** [comment] 2021-01-02 20:54
> 
> 
> Pazer stated in my duplicate of this issue that there's some technical issues with this bug because you cant tell in console who started the vote/who its against. I have a slightly crude idea that may work for a fix.
> 
> When the bot detector sends out the command to attempt the vote kick, you could have a generic command go with it, like a help command, sort of like a ping. (or maybe even just the auto generated password, which would return as unknown command, but then it could see if your bot detector started the vote) Then if the bot detector sees the pong of that generic command and vote kick started, it can start a 2 minute cooldown and you can attach anything else to that such as chat messages warning there's still a cheater.
> 
> It wouldn't be perfect but it could be a temporary band aid.

The tool knows when it sends a votekick, right? There's no need to send a chat message to remind itself that it has sent a vote, if that's what you're suggesting.

**Comment by ClusterConsultant** [comment] 2021-01-02 20:57
> But if the bot detector could see a vote started

It has no way of knowing that. The only thing the tool knows is when a user joins a lobby, when it calls a votekick, and when a user leaves a lobby. 

> I feel like the chances are pretty low that someone else starts a vote at the same time as the detector

They are actually incredibly high, both users and the tool try to rid a lobby of bots as quickly as possible. Not to mention the other team and other TF2BD users. Also we do not know how long a vote would take to complete. That time can range significantly. 

> The tool knows when it sends a votekick, right? There's no need to send a chat message to remind itself that it has sent a vote, if that's what you're suggesting.

Correct, this would be equivalent to just starting a timer whenever the command is sent.

**Comment by RedxYeti** [comment] 2021-01-02 21:02
> The tool knows when it sends a votekick, right? There's no need to send a chat message to remind itself that it has sent a vote, if that's what you're suggesting.

I'm trying to find a way to verify your bot detector sent the vote start, due to the lack of information in the console during votes. Looks like my idea won't work though.

**Comment by kotx** [comment] 2021-01-02 21:15
> 
> 
> > The tool knows when it sends a votekick, right? There's no need to send a chat message to remind itself that it has sent a vote, if that's what you're suggesting.
> 
> I'm trying to find a way to verify your bot detector sent the vote start (of the vote that's currently happening), due to the lack of information in the console during votes. Looks like my idea won't work though.

Can't really verify a votekick (sent by you) with a chat message (sent by you). The detector itself knows it has started a vote. However, a chat message could help for communication between bot detectors to know that another bot detector has started a vote.

**Comment by PazerOP** [comment] 2021-01-02 22:48
Thanks for all the brainstorming going on here. This actually does give me a few ideas that could be integrated into an upcoming version of tf2bd without too much work.

You're right that the tool does indeed know if *we* were able to start a votekick. There is a unique usermessage type that gets sent to the player if they tried to call a vote, and it failed to start for any reason. So the absense of that usermessage indicates that a vote was indeed called. The end of that vote can start a 2 minute timer before additional votes are attempted.

**Comment by ClusterConsultant** [comment] 2021-03-03 17:09
The attempted fix here was simply non-viable. Usermessages are just waaaay to unreliable to do anything with. Likely is going to have to wait until demo support again

**Comment by PazerOP** [comment] 2021-03-05 22:58
A bandaid fix was applied in 4717773915638b6f3f8f2696f2794c3b3f1feee2. A hud mod (courtesy of ClusterConsultant, moeb, CrazyGunman) simply hides the "vote failed" popup, and mutes the sound. This resolves all the symptoms of this issue. 

Given the failure that was #266, I think this is probably as good as it's going to get.

**Closed by PazerOP** 2021-03-05 22:58 UTC
Labels: Priority: High, Type: Enhancement
