### ISSUE TITLE
Cheater Found Announcement Timer.

### ISSUE THREAD

**Issue by codyv1875** [PazerOP/tf2_bot_detector#202] opened 2020-09-04 03:38 UTC
As much as I love the auto-announce feature, I do think it is a wee bit too fast. Some players have been quite vocal that they didn't care for the spammy messages. SO! I was wondering if there was some way for there to be a sort of slider to set the timings for when these messages went out? Without going right into the code and changing it myself. I'm not sure if I'm the only one who has had this issue, so here I am. Seems like a QOL sort of thing. Cheers!

**Comment by ClusterConsultant** [comment] 2020-09-04 03:40
Duplicate of #70 with a related pull of #187

**Closed by ClusterConsultant** 2020-09-04 03:40 UTC
Labels: Type: Duplicate
