### ISSUE TITLE
"Client stuck on object #" 

### ISSUE THREAD

**Issue by JONTTM** [PazerOP/tf2_bot_detector#298] opened 2021-03-06 02:23 UTC
This message appears in the top-right corner all the time while playing the game with bot detector running. I have never seen the message appear when TF2 was not launched via bot detector. I usually see the message when I am standing next to the payload cart (implying that I am getting stuck on the cart), but I don't know why it only appears when using bot detector. I am using the default hud (normal mode - not minimized). 

I will upload a screenshot here when I play later today.

**Comment by PazerOP** [comment] 2021-03-06 02:56
Duplicate of #221.

The `Con_NPrintf` display showing up is an unfortunate side effect of running in developer mode. I don't think there's any way to resolve this, short of making the font invisible via a hud mod, but then who knows what else that could break. It doesn't help much but you can use `con_nprint_bgalpha 0` (default 50) to hide the background, which might make it a bit less noticeable.

The only reason developer mode is used right now is to know when we have actually picked a class (and therefore are actually in the game and ready to call votes), since picking classes runs `exec classname.cfg`, and in developer mode, all cfg execs are printed to the console. 

There may be an alternative to enabling developer mode: tracking `_cl_classmenuopen` for when it transitions from 1 -> 0.

**Closed by PazerOP** 2021-03-06 02:56 UTC
Labels: Priority: Medium, Type: Bug, Type: Duplicate

**Comment by ClusterConsultant** [comment] 2021-03-06 03:12
should be noted one could append an echo to class cfgs to get the same effect. Just would require finding the class cfgs and doing a dumb append.

**Comment by PazerOP** [comment] 2021-03-06 03:14
Some people have pretty extensive/complex class configs, and I believe mastercomfig hides the original `classname.cfg`, instead wanting you to use `user_classname.cfg` or something like that.

**Comment by ClusterConsultant** [comment] 2021-03-06 03:16
in the case of mastercomfig it's just in a subfolder, cfg/user/classname.cfg. No matter the complexity some form of cfg/classname.cfg is run. If it is not it's because it isn't present
