### ISSUE TITLE
Spammed with a vote cooldown message bug [Bug]

### ISSUE THREAD

**Issue by MetroidMaster28** [PazerOP/tf2_bot_detector#234] opened 2020-12-23 19:25 UTC
**Describe the bug**
> A clear and concise description of what the bug is.
For some reason when a bot joined it just spammed the text on the side of my screen saying "You cannot call another vote because you called one 12 seconds ago." or something like that. The number didn't go out and I then tried to do a vote and the vote menu was up and I could start a call vote but it still said that there was 12 seconds.
**To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Logs**
> Add any relevant logs. Logs are found by going to File → Open Logs Folder

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
> - OS: [e.g. Windows 10, 8, 7]
> - Version of bot detector [e.g. 1.1.0.674]

**Additional context**
> Add any other context about the problem here.

**Comment by ClusterConsultant** [comment] 2021-01-01 06:33
Which version are you on? Are you able to reproduce this reliably enough to post a debug report? Also I am unclear if you were able to manually call a vote or if when you tried manually it just gave you the cool down countdown.

**Comment by RedxYeti** [comment] 2021-01-02 20:08
Pazer stated in my duplicate of this issue that there's some technical issues with this bug because you cant tell in console who started the vote/who its against. I have a slightly crude idea that may work for a fix. 

When the bot sends out the command to attempt the vote kick, you could have a generic command go with it, like a help command, sort of like a ping. Then if the bot sees the pong of that generic command and vote kick started, it can start a 2 minute cooldown and you can attach anything else to that such as chat messages warning there's still a cheater.

It wouldn't be perfect but it could be a temporary band aid.

**Comment by ClusterConsultant** [comment] 2021-01-02 20:11
@RedxYeti I think you may be looking for #168

**Comment by RedxYeti** [comment] 2021-01-02 20:27
> @RedxYeti I think you may be looking for #168

yeah I was, I removed my comment and posted it there.

**Comment by ClusterConsultant** [comment] 2021-01-22 00:07
This is suspected to have been fixed with the implementation of a vote timer. Please comment if that is not the case. This issue will be closed on 25/01/2021 if nothing more is heard

**Closed** 2021-01-27 16:08 UTC
Labels: Status: Tentatively Fixed, Type: Bug
