### ISSUE TITLE
Change the message that is put in chat when a bot joins the other team

### ISSUE THREAD

**Issue by Spygineer2** [PazerOP/tf2_bot_detector#97] opened 2020-06-21 14:38 UTC
I would like to change the message to "kick your bot", or just disable the message in chat.

**Comment by karlovchap** [comment] 2020-06-30 23:40
just disable chat messages in your copy of TF2BD, Spygineer

**Comment by DiegoFleitas** [comment] 2020-07-01 23:42
I made a similar request too https://github.com/PazerOP/tf2_bot_detector/issues/70

**Comment by ClusterConsultant** [comment] 2020-07-02 05:09
Duplicate of issue #70

**Closed by ClusterConsultant** 2020-07-02 05:09 UTC
