### ISSUE TITLE
Identify bots dynamically

### ISSUE THREAD

**Issue by 107zxz** [PazerOP/tf2_bot_detector#63] opened 2020-06-06 14:36 UTC
Certain TF2 bot software features "AntiCheat" functionality, where it will automatically call out hackers based on their actions in game, to avoid hack vs hack situations. Hopefully you can integrate dynamic cheat detection like these.

Here is the source code for the method used in the open-source TF2 "catbots":
https://github.com/nullworks/cathook/blob/master/src/hacks/AntiCheat.cpp

**Comment by randrade86** [comment] 2020-06-06 18:44
I believe that one major problem with this is that you can't "read" the game and detect cheaters without reading the game memory or doing any kind of injection. This may cause VAC-Bans is the tool is blacklisted

**Comment by 107zxz** [comment] 2020-06-07 01:06
Good point.

**Comment by PazerOP** [comment] 2020-06-07 07:23
Monitoring of network traffic may be added in a later version by reading it out of demo files. See one of my other repos, [DemoLib2](https://github.com/PazerOP/DemoLib2).

**Comment by ClusterConsultant** [comment] 2020-07-02 06:31
Duplicate of #57

**Closed by ClusterConsultant** 2020-07-02 06:31 UTC
