### ISSUE TITLE
Vote Kick Started Success cool down

### ISSUE THREAD

**Issue by RedxYeti** [PazerOP/tf2_bot_detector#240] opened 2021-01-01 01:10 UTC
I see too late people have already brought this up, you can close this.

When the bot detector you're running successfully calls a vote, but there are multiple bots on your team, the detector keeps trying to call a vote even though there's a 2 minute cool down. This leaves a prompt on your screen saying you cant call another vote for 2 minutes, 1 minute etc.

A solution would be to add a 2 minute cool down after a successful vote started by your detector and maybe a chat message describing that theres still a bot on the team and that youve already called a vote and cannot call another vote for x amount of time.

**Comment by cyrusParvereshi** [comment] 2021-01-01 05:29
I agree it's super annoying because if you mark the bot as a cheater then it constantly keeps annoying u with the cooldown prompt.

**Comment by PazerOP** [comment] 2021-01-01 06:13
Hi, thanks for making this issue. Unfortunately, there are some technical challenges with this, mostly arising from the fact that you can't tell from console output who initiated a vote, and who the votekick is against.

Duplicate of #168.

**Closed by PazerOP** 2021-01-01 06:13 UTC
Labels: Priority: Low, Type: Enhancement
