### ISSUE TITLE
[BUG] Program is unable to find important command-line parameters

### ISSUE THREAD

**Issue by UAVXP** [PazerOP/tf2_bot_detector#331] opened 2021-06-22 17:34 UTC
**Describe the bug**
After the latest TF2 update, which has been released on 22'nd of June, 2021, TF2 Bot Detector cannot properly connect with the game

**To Reproduce**
1. Update TF2 after 22'nd of June, 2021
2. Run Bot Detector
3. Press "Launch TF2"

**Expected behavior**
Runned TF2

**Logs**
No significant log errors found

**Screenshots**
![image](https://user-images.githubusercontent.com/3075683/122972380-bfb91680-d398-11eb-98d8-bef1e06757ff.png)

**Desktop**
- OS: Windows 7
- TF2 Bot Detector v1.2.0.798

**Additional context**
Before the latest TF2 update everything was working fine

**Comment by jmke79** [comment] 2021-06-22 18:54
able to replicate on Windows 10 also; exact same issue

**Comment by Spygineer2** [comment] 2021-06-22 19:41
I am having the same issue

**Comment by Susorodni** [comment] 2021-06-22 23:14
With the recent update, also having the same issue

**Comment by Koi-Code-TF2** [comment] 2021-06-23 00:50
This issue is _likely_ caused by the TF2 update breaking or removing the steam://run functionality entirely

**Comment by PazerOP** [comment] 2021-06-23 19:36
I've been very busy lately, which is why there hasn't been any activity lately. I'll try to implement a fix this evening.

**Comment by WizardEngineer** [comment] 2021-06-23 21:43
Wouldn't a work around be to create a batch file with the said command line paramaters to open the application. You'd just need to similarly set the launch options to be similar to what was presented already but with the batch file.

**Comment by Jesseman1** [comment] 2021-06-23 21:52
crap, I just realized I probably should have just commented here instead of posting a whole new issue about it. But yeah, I don't know if I can follow Koi's guide cuz those fields are not in my file...

**Comment by Koi-Code-TF2** [comment] 2021-06-23 22:00
> those fields are not in my file...

Assuming you are in the right file (localconfig.vdf), then the reason your 440 doesn't have a "LaunchOptions" field is because you have never set advanced launch options ever before. Either you can manually add the field yourself, or the easier method would just be to add one adv launch option via the built in menu in steam. Doing so should cause the field to be generated. I hope this helps

**Comment by Jesseman1** [comment] 2021-06-23 22:10
> Assuming you are in the right file (localconfig.vdf), then the reason your 440 doesn't have a "LaunchOptions" field is because you have never set advanced launch options ever before. Either you can manually add the field yourself, or the easier method would just be to add one adv launch option via the built in menu in steam. Doing so should cause the field to be generated. I hope this helps

I have advanced launch options already in place from using mastercoms' comfig. So I don't know why the field is not already there, unless there is some *other* launch options box that I don't know about.

**Comment by Koi-Code-TF2** [comment] 2021-06-23 22:14
> I have advanced launch options already in place from using mastercoms' comfig. So I don't know why the field is not already there, unless there is some _other_ launch options box that I don't know about.

Advanced launch options are _normally_ placed in the following location: In steam, right click on TF2 in your library, then click on properties. In the General tab, there will be a section labeled "Launch Options". The reason I do not advise just copy+pasting the full string of TF2BD's launch options into that location is what I described above:

> Pazer, I do not recommend doing this because the launch options are too long. There is a visual bug within the steam interface which cuts the launch options short. **Technically** they are still present and will still work, but they are not visible or modifiable beyond a certain point, so do this at your own risk. It likely won't cause any serious issue but just know that it's a problem

**Comment by Jesseman1** [comment] 2021-06-23 22:14
yes, I already have some inputs there for the comfig

**Comment by Koi-Code-TF2** [comment] 2021-06-23 22:36
> yes, I already have some inputs there for the comfig

If this is the case, and you are sure you still don't have any LaunchOptions field inside the localconfig.vdf file for TF2, then I am not sure. Perhaps this is caused by steam cloud sync not syncing it correctly? You can either manually add the field to the file as mentioned before, or alternatively you can try the other method by copy+pasting the full args directly into the launch options area inside the steam interface. Just be aware that they will NOT all show up - some will be invisible because the arguments are too long. Still worth a try though

**Closed** 2021-06-25 04:21 UTC
Labels: Priority: Critical, Type: Bug
