### ISSUE TITLE
Problem with temp fix [BUG]

### ISSUE THREAD

**Issue by Jesseman1** [PazerOP/tf2_bot_detector#333] opened 2021-06-23 21:43 UTC
**Describe the bug**
> My localconfig.vdf file does not have the launch options section in it, and I don't want to break TF2 or Steam by trying to do it myself and getting it wrong.

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to localconfig.vdf
> 2. Scroll down to "440"
> 3. See no "launchOptions" or "Launch Options go here" fields.

**Expected behavior**
> I was hoping to follow the guide and see the exact place to type in my launch options.

**Screenshots**
> ![LocalConfig error](https://user-images.githubusercontent.com/26986519/123171215-7d9bdd80-d449-11eb-8ac6-e732627225c6.jpg)

**Desktop**
> - OS: Windows 10
> - Version of bot detector: 1.2.0.798

**Additional context**
> I apologize for making a Git Issue for this instead of asking in the Discord server, but Discord disabled my 5 year old account last week(never would tell me what I did) and won't let me verify with my phone again.

**Comment by Spygineer2** [comment] 2021-06-23 21:50
This just means you haven't added any launch options to tf2 yet. You can just add a launch option to TF2 using steam to fix this, or you can add "LaunchOptions" underneath "PlayTime" to fix it as well.

**Comment by Jesseman1** [comment] 2021-06-23 21:53
but I *have* added launch options to TF2, I use the ones Mastercoms says to use when running the Comfig

**Comment by WizardEngineer** [comment] 2021-06-23 21:56
> 
> 
> but I _have_ added launch options to TF2, I use the ones Mastercoms says to use when running the Comfig

they aren't referring to those launch options, the launch options that are used for the program are what you are missing in order to open TF2BD

the ones you have in steam are alright, they will be executed along with whatever you have put into `LaunchOptions` or in a `.bat` file

**Comment by Jesseman1** [comment] 2021-06-23 22:02
Ok, so I put "launchOptions" below playtime, now the "launch options go here" bit, that goes beside just like "46" does above?

**Comment by Spygineer2** [comment] 2021-06-23 22:07
Yeah, it should look something like this:
```
"440"
{
	"LastPlayed"		"1624484106"
	"Playtime"		"46"
	"LaunchOptions"	"(Launch options here) "
						
}
```

**Comment by Jesseman1** [comment] 2021-06-23 22:36
Ok, so I tried putting the commands in this file as instructed and it did not work. However I then copied the commands and posted them into the actual launch options box through Steam and now the BD seems to be working.

Also if anyone knows how I can get Discord to let me verify this new account I would really appreciate it.

**Comment by Jesseman1** [comment] 2021-06-23 23:17
Ok still not completely fixed yet. I used these commands "-usercon +ip 0.0.0.0 +rcon_password [pass] +hostport [port]" Since Creyon said that was all that was needed. The BD is able to launch and read chat, but cannot see player names. What commands do I need to add to make this work correctly?

**Comment by Spygineer2** [comment] 2021-06-23 23:44
Try copying all of the launch commands that Koi posted and pasting them into notepad. Then add your rcon password and host port. Then copy them and paste them into the launch options fiend in steam.

**Comment by Jesseman1** [comment] 2021-06-23 23:59
I thought people were saying there are problems with the command list being too long. Do I need all of them or are there some that aren't necessary?

**Comment by Spygineer2** [comment] 2021-06-24 00:04
It should work fine if you paste them in instead of typing them.

**Comment by Jesseman1** [comment] 2021-06-24 00:12
Just tried it, didn't work

**Comment by Jesseman1** [comment] 2021-06-24 00:19
huh, ok this time it did.

**Comment by PazerOP** [comment] 2021-06-25 03:12
Duplicate of #331

**Closed by PazerOP** 2021-06-25 03:12 UTC
Labels: Priority: Medium, Type: Bug
