### ISSUE TITLE
[Suggestion] Linux version?

### ISSUE THREAD

**Issue by Nika03** [PazerOP/tf2_bot_detector#272] opened 2021-01-26 09:25 UTC
I personally started playing TF2 on Manjaro Linux for better performance and control over the OS. I would love to have TF2BD on Linux so I can continue fighting cheaters and bots.

**Comment by ClusterConsultant** [comment] 2021-01-26 09:29
dupe of #56

**Closed by ClusterConsultant** 2021-01-26 09:29 UTC
