### ISSUE TITLE
Don't auto launch TF2 when an update is available

### ISSUE THREAD

**Issue by Jonttm** [PazerOP/tf2_bot_detector#153] opened 2020-07-17 03:40 UTC
> wait for update check before auto launching
> if an update is available, don't launch

(this only applies if user has update checks enabled)

**Comment by PazerOP** [comment] 2020-07-17 17:35
Duplicate of https://github.com/PazerOP/tf2_bot_detector/projects/2#card-41277839.

**Closed by PazerOP** 2020-07-17 17:35 UTC
Labels: Type: Duplicate
