### ISSUE TITLE
Wait for people to join before initiating a vote

### ISSUE THREAD

**Issue by Czechball** [PazerOP/tf2_bot_detector#122] opened 2020-07-04 04:10 UTC
As of now, the script will call a votekick even when there aren't enough people actually in-game in your team so it automatically fails. It would be nice to wait for enough people to actually join your team before initiating a vote.

**Comment by PazerOP** [comment] 2020-07-10 21:21
How long should it wait? I'm thinking ~15 seconds or so?

**Comment by The-personified-devil** [comment] 2020-07-10 21:31
> How long should it wait? I'm thinking ~15 seconds or so?
I thought the point was waiting till enough people have fully joined? Or do you want to give them a few seconds between joining and getting the vote displayed?

**Comment by PazerOP** [comment] 2020-07-11 03:35
This should be at least partially solved by #134, but it's difficult for me to get into a situation where I can test this.

**Comment by The-personified-devil** [comment] 2020-07-11 06:46
You can setup a dedicated server on the same pc as the game itself and it has only minuscule performance impact (It sadly takes a few hours to download.). There is also a command to change the time between votes (`sv_vote_creation_timer`, `sv_vote_failure_timer`) and another one to change the required amount of players that vote yes so that only two persons are required (`sv_vote_quorum_ratio`). I believe you can kick bots so just add a few and call votes with the ratio for two person kicks. Then change the ratio in the tool and invite a friend to join the server. I think that should be enough to test the tool.

**Comment by ClusterConsultant** [comment] 2020-07-11 06:47
If you need a server to test on you can reach out to me. I host one for matches

**Comment by PazerOP** [comment] 2020-07-11 07:07
I'm fairly certain the code I added in #134 will handle the quorum just fine in a "simple" situation where nobody is connecting. However, the specific situation I was referring to as difficult to test was:
* cheater(s) on my team
* enough players on my team to successfully pass a vote, but
* enough additional players are connecting to my team (but not yet in the game) that them not voting would cause the quorum check to fail

**Comment by The-personified-devil** [comment] 2020-07-11 10:13
I don't know how resource intensive the text mode is. Otherwise you could use that to simulate the problem. But I think the best way to do the whole thing is to feed fake responses to the program simulating the problem. If it's implemented correctly it will be transferable to normal usage of the tool.

**Comment by PazerOP** [comment] 2020-07-11 19:51
After spamming the casual queue for a bit, I was able to replicate this (even with the fixes from #134). I think it may be unavoidable to have an arbitrary delay, since I think the issue is that the vote is being called after people have connected to the server (they show as "active" in `status` output), but before they have joined a team/picked a class. I think this causes the vote UI to not show up for them, so they miss out on the ability to participate.

Since there's no way of determining their class/ingame status from the console output, I don't see a way around this besides adding a delay that gives them some time to get into the server and onto a team.

**Comment by ParzivalWolfram** [comment] 2020-07-15 02:06
You could potentially use the suspicion timer for this, as users are always well in-game before the suspicious status is cleared.

**Comment by PazerOP** [comment] 2020-08-01 02:27
Closing this issue, since I think 1a0e9f0 is as good as its going to get for now.

**Closed by PazerOP** 2020-08-01 02:27 UTC
Labels: Priority: Medium, Type: Enhancement
