### ISSUE TITLE
Allow binding the bot on other team chat message instead of spam

### ISSUE THREAD

**Issue by kittenchilly** [PazerOP/tf2_bot_detector#256] opened 2021-01-09 04:09 UTC
I have gotten kicked my fair share of times for the spam associated with the regular interval chat message that says there's a bot on the opposite team. I think instead of having it be chatted regularly in intervals, it should automatically chat once, and then allow you to post it more times with a set key bind.

**Comment by brachistosaurus** [comment] 2021-01-09 04:36
May be a duplicate of #207, but _ClusterConsultant_ said this: "different enough to stand on its own, in the future please make separate issues for separate suggestions."

So, maybe that issue could be closed, and this issue could be left up.

**Comment by ClusterConsultant** [comment] 2021-01-09 10:44
Moving this over to #207 as there is more existing discussion there.

Also, you can turn off the messages currently.

**Closed by ClusterConsultant** 2021-01-09 10:44 UTC
