### ISSUE TITLE
"client stuck on object 0/" error in Casual

### ISSUE THREAD

**Issue by tariqmudallal** [PazerOP/tf2_bot_detector#222] opened 2020-10-27 19:23 UTC
![image](https://user-images.githubusercontent.com/9893082/97351355-de3d3100-184e-11eb-80a1-05deadba32ca.png)

As you see in the image, I get the aforementioned error on the top right when I play casual with TF2BD open every time I get into a Casual game.

**Comment by ClusterConsultant** [comment] 2020-11-02 08:34
duplicate of #221

**Closed by ClusterConsultant** 2020-11-02 08:34 UTC
Labels: Type: Duplicate
